#!/usr/bin/env python

import distance, sys, time, random

if __name__ == '__main__':
	limit = 0
	runs = []
	repeat = 10

	if len(sys.argv)>= 2:
		repeat = int(sys.argv[1])
	if len(sys.argv)>= 3:
		limit = int(sys.argv[2])

	f = open("blogtitles.txt")
	l = f.readlines()
	f.close()

	for i in range(repeat):
		s = l[random.randint(0,len(l)-1)].strip()

		t = time.time()
		for line in l:
			if limit:
				distance.distance3(s,line,limit)
			else:
				distance.distance(s,l)
		runs.append(time.time()-t)

	avg = reduce(lambda x, y: x+y, runs) / repeat

	print "Time to compare %d titles: %.3fs, %.3fs, %.3fs (min, max, avg)" % (len(l), min(runs), max(runs), avg)
